@startuml class-diagram
class User << Entity >> {
   
    + name: string
    + password: string 
    + email: string
    + age: int
    + adress:string
    + shares: []
    + socialNetworks: []
    + likeShare()
    + addFriend()
    + sendMessage()
    + sharePost()
    }



class Share << Entity >> {
    + name: string
    + type: string
    + shares: []
}

class Photo  extends Share  {
    + name: string
    + type: string
}

class Video extends Share {
    + name: string
    + type: string
}

class Story extends Share {
    + name: string
    + type: string
}

class Idea extends Share {
    + name: string
    + type: string
}

class SocialNetwork {
    + name: string
    + participants: []
    + showParticipant()
} 

User " 0..* " --- "1" SocialNetwork
User " 1 " -- " 0..* " Share


@enduml